# action.yml
name: 'Push main branch to Dokku'
description: 'Easily deploy an app to your Dokku Instance'
author: 'Olivier Brassard'
branding:
  icon: 'send'  
  color: 'purple'
inputs:
  dokku_repo: 
    description: "The dokku app's git repository url (in SSH format)"
    required: true
  ssh_key: 
    description: 'A private SSH key that has push acces to your Dokku instance'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/app/entrypoint.sh'
  post-entrypoint: '/app/dokku-unlock.sh'
  post-if: cancelled()
  env:
    SSH_PRIVATE_KEY : ${{ inputs.ssh_key }}
    DOKKU_REPO : ${{ inputs.dokku_repo }}
